apiVersion: v1
kind: Service
metadata:
  name: a
  labels:
    app: a
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: grpc-svc
  selector:
    app: a

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: a
  labels:
    app: a
spec:
  selector:
    matchLabels:
      app: a
  replicas: 1
  template:
    metadata:
      labels:
        app: a
    spec:
      containers:
      - name: a
        image: ccr.ccs.tencentyun.com/koderover-rc/myapp-1-grpc:v0.1-6-g227364d
        imagePullPolicy: Always
        command: ["/myapp-1-grpc"]
        args: ["--downstream-addr", "$(DOWNSTREAM_ADDR)", "--headers", "$(HEADERS)"]
        env:
        - name: DOWNSTREAM_ADDR
          value: "b:80"
        - name: HEADERS
          value: "x-request-id"
        ports:
        - containerPort: 8080
          name: grpc-svc
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
