apiVersion: v1
kind: Service
metadata:
  name: b
  labels:
    app: b
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: grpc-svc
  selector:
    app: b

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: b
  labels:
    app: b
spec:
  selector:
    matchLabels:
      app: b
  replicas: 1
  template:
    metadata:
      labels:
        app: b
    spec:
      containers:
      - name: b
        image: ccr.ccs.tencentyun.com/koderover-rc/myapp-2-grpc:v0.1-6-g227364d
        imagePullPolicy: Always
        command: ["/myapp-2-grpc"]
        args: ["--downstream-addr", "$(DOWNSTREAM_ADDR)", "--headers", "$(HEADERS)"]
        env:
        - name: DOWNSTREAM_ADDR
          value: "c:80"
        - name: HEADERS
          value: "x-request-id"
        ports:
        - containerPort: 8081
          name: grpc-svc
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
