apiVersion: v1
kind: Service
metadata:
  name: c
  labels:
    app: c
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: grpc-svc
  selector:
    app: c

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: c
  labels:
    app: c
spec:
  selector:
    matchLabels:
      app: c
  replicas: 1
  template:
    metadata:
      labels:
        app: c
    spec:
      containers:
      - name: c
        image: ccr.ccs.tencentyun.com/koderover-rc/myapp-3-grpc:v0.1-6-g227364d
        imagePullPolicy: Always
        command: ["/myapp-3-grpc"]
        ports:
        - containerPort: 8082
          name: grpc-svc
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
